Entities/Ask.cs
using System;
using System.Collections.Generic;

namespace Lawyer.Entities
{
	public class Ask
	{
		public Guid Id { get; set; }

		public string Slug { get; set; }

		public string Title { get; set; }

		public string Body { get; set; }

		public DateTime Date { get; set; }

		public User Author { get; set; }

		public bool IsAnswered { get; set; } 

		public ICollection<Answer> Answers { get; set; }
	}
}

Controllers/AskController.cs
using Lawyer.Models;
using Lawyer.ServiceManagers;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;


namespace Lawyer.Controllers
{
	[Authorize]
	public class AskController : Controller
	{
		private readonly ServiceManager _serviceManager = new ServiceManager();

		public ActionResult AddQuestions()
		{
			return View(new AskModel());
		}

		[HttpPost]
		public ActionResult AddQuestions(AskModel model, string returnUrl)
		{
			if (ModelState.IsValid)
			{
				var userId = User.Identity.GetUserId();
				_serviceManager.Asks.AddAsk(model, userId);
				//return RedirectToAction("Index", "Home");

				returnUrl = !string.IsNullOrEmpty(returnUrl) ? returnUrl : "/";
				return Redirect(returnUrl);
			}
			//return View(model);

			return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AddAnswer(AnswerModel model, string returnUrl)
		{
			if (ModelState.IsValid)
			{
				var userId = User.Identity.GetUserId();
				_serviceManager.Asks.AddAnswer(model, userId);

				returnUrl = !string.IsNullOrEmpty(returnUrl) ? returnUrl : "/";
				return Redirect(returnUrl);
			}

			return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		}

		[AllowAnonymous]
		public ActionResult LastAsks(int count = 20)
		{
			var userId = User.Identity.GetUserId();

			var lastAsks = _serviceManager.Asks.GetLastAsks(count);
			
			return View("LastAsks", lastAsks);
		}

		[AllowAnonymous]
		public ActionResult LastAsksWithAnswer(int count = 20)
		{
			var userId = User.Identity.GetUserId();

			var lastAsks = _serviceManager.Asks.GetLastAsksForUser(count);

			return View("LastAsksWithAnswer", lastAsks);
		}


		[AllowAnonymous]
		public ActionResult ShowAnswer(string slug)
		{
			var model = _serviceManager.Asks.FindBySlug(slug);

			if (model == null)
			{
				return HttpNotFound();
			}

			return View(model);
		}

		[AllowAnonymous]
		public ActionResult Show(string slug)
		{
			var model = _serviceManager.Asks.FindBySlug(slug);

			if (model == null)
			{
				return HttpNotFound();
			}

			return View(model);
		}



		[HttpPost]
		public ActionResult EditButton( string slug)
		{
			
			try
			{
				_serviceManager.Asks.SetIsAnswered(slug);
				return RedirectToAction("LastAsks");
			}
			catch
			{
				return RedirectToAction("LastAsks");
			}
		}
	}
}

Views/Ask/AddQuestions.cshtml
@model Lawyer.Models.AskModel
@{
	ViewBag.Title = "Questions";
}


<div class="container">
	<div class="row">
		<h1 class="text-center"> @Model.Body </h1>
		<p class="text-justify">
			@Html.Raw(Model.Body)
		</p>
		<div>
			<form action="/ask/addquestions" method="post">
				<p><text>Краткое описание вопроса: </text></p>
				@Html.ValidationMessageFor(x => x.Title)
				<div class="form-row input-group my-2">
					<input class="form-control" type="text" id="title" name="title" value="@Model.Title" placeholder="Title" />
				</div>
				<p><text>Вопрос: </text></p>
				<textarea name="Body" cols="50" rows="3"></textarea>
				<input type="hidden" name="returnUrl" value="@Request.Url.AbsoluteUri" />
				@Html.AntiForgeryToken()
				<p><input type="submit" value="Написать" /></p>
			</form>
		</div>
	</div>
</div>

Views/Ask/LastAsks.cshtml
@model List<Lawyer.Models.AskModel>
@{
	ViewBag.Title = "Список вопросов";
}
<body class="text-justify">
	<div class="container">


		@foreach (var post in Model)
		{
			string postUrl = Url.Action("show", "ask", new RouteValueDictionary(new { slug = post.Slug }), Request.Url.Scheme, Request.Url.Host);

		<p class="lead">
			@post.Title
			<br>
			<a href="/ask/show/@post.Slug" class="card-link">Перейти к вопросу </a>
		</p> <br>
		}
	</div>
</body>

Views/Ask/LastAsksWithAnswer.cshtml
@model List<Lawyer.Models.AskModel>
@{
	ViewBag.Title = "Список вопросов";
}
<body class="text-justify">
	<div class="container">


		@foreach (var post in Model)
		{
			string postUrl = Url.Action("showanswer", "ask", new RouteValueDictionary(new { slug = post.Slug }), Request.Url.Scheme, Request.Url.Host);

			<p class="lead">
				@post.Title
				<br>
				<a href="/ask/showanswer/@post.Slug" class="card-link">Перейти к вопросу </a>
			</p> <br>
		}
	</div>
</body>

Views/Ask/Show.cshtml
@model Lawyer.Models.AskModel
@{
	ViewBag.Title = Model.Title;
}

<div class="container">
	<h4 class="text-center"> @Model.Title </h4>
	<p class="text-justify">
		@Html.Raw(Model.Body)
	</p>
	@if (User.Identity.IsAuthenticated)
	{
		<div>
			<form class="form-group" action="/ask/addanswer" method="post">
				@Html.AntiForgeryToken()
				<textarea class="form-control" name="text" cols="50" rows="2" placeholder="Дать ответ"></textarea>
				<input type="hidden" name="askId" value="@Model.Id" />
				<input type="hidden" name="returnUrl" value="@Request.Url.AbsoluteUri" />
				<input class="btn btn-dark my-2" type="submit" value="Написать" />


			</form>
		</div>
	}
	<div>
		@foreach (var comment in Model.Answers)
		{
			<div class="border my-2 p-2">
				<div>
					@comment.Text
				</div>
				<div class="text-right text-info">
					@comment.Date.ToLongDateString() - @comment.Date.AddHours(3).ToLongTimeString()
				</div>
			</div>
		}
	</div>
</div>



@using (Html.BeginForm("EditButton", "Ask", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Ask</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.Slug)

		<div class="form-group">
			@Html.LabelFor(model => model.IsAnswered, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				<div class="checkbox">
					@Html.EditorFor(model => model.IsAnswered)
					@Html.ValidationMessageFor(model => model.IsAnswered, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-dark my-2" />
			</div>
		</div>
	</div>
}

Views/Ask/ShowAnswer.cshtml
@model Lawyer.Models.AskModel
@{
	ViewBag.Title = Model.Title;
}

<div class="container">
	<h4 class="text-center"> @Model.Title </h4>
	<p class="text-justify">
		@Html.Raw(Model.Body)
	</p>

	<div>
		@foreach (var comment in Model.Answers)
		{
			<div class="border my-2 p-2">
				<div>
					@comment.Text
				</div>
				<div class="text-right text-info">
					@comment.Date.ToLongDateString() - @comment.Date.AddHours(3).ToLongTimeString()
				</div>
			</div>
		}
	</div>
</div>